### ISSUE TITLE
EventPoster name change?

### ISSUE THREAD

**Issue by IbrahimBilal2005** [IbrahimBilal2005/CampusPulse#21]
After a few discussions with team members and external sources, "EventPoster" sounds like a "poster" for an event. Do we need a name change? Maybe to something like EventCreator?

I raised this as an issue since we'll need everyone's opinion, and changing the name will require adjusting many files and variable names, potentially causing merge conflicts that we'll have to account for beforehand.

**Comment by W-Akrabi** [comment]
I believe the name is fine if we add the java docs into the file
